# set up variables from settings.script

source ../../settings.script

# set up package variables

SCRIPTDIR="$PWD"
PKG=$(basename $PWD)
ARC="$PKG.tar.xz"

# move to source folder

cd "/sources/$LFSVS"

# clean up leftover build-folders

if [ -a "/sources/$LFSVS/$PKG" ]
  then
    rm -rf "$PKG"
  fi

# unpack package

tar -xf "$ARC"
cd "$PKG"

# configure, build and install

./configure --prefix=/tools

make

make check

make install

# clean up

rm -rf "/sources/$LFSVS/$PKG"
