# set up variables from settings.script

source ../../settings.script

# set up package variables

SCRIPTDIR="$PWD"
PKG="linux-4.4.2"
ARC="$PKG.tar.xz"

# move to source folder

cd "/sources/$LFSVS"

# unpack kernel

if [ ! -a "/sources/$LFSVS/$PKG" ]
  then
    tar -xf "$ARC"
  fi

cd "$PKG"

# make and install

make mrproper

make INSTALL_HDR_PATH=dest headers_install
cp -rv dest/include/* /tools/include
