# set up variables from settings.script

source ../settings.script

# set up package variables

PTH=$(dirname $PWD)
PKG=$(basename $PWD)
URL=(
"http://hostap.epitest.fi/releases/wpa_supplicant-2.5.tar.gz"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"libnl-3.2.27"
"openssl-1.0.2g"
)

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root
