cd ../kde/plasma

source_path=$PWD

while read -r line; do

    # Get the file name, ignoring comments and blank lines
    if $(echo $line | grep -E -q '^ *$|^#' ); then continue; fi
    file=$(echo $line | cut -d" " -f2)

    pkg=$(echo $file|sed 's|^.*/||')          # Remove directory
    packagedir=$(echo $pkg|sed 's|\.tar.*||') # Package directory

su -l "$(getent passwd | awk -F: '$3 == 1000 {print $1}')" << EOF

    cd "$source_path"

    tar -xf "$file"
    pushd "$packagedir"

      mkdir build
      cd    build

      cmake -DCMAKE_INSTALL_PREFIX=$KF5_PREFIX \
            -DCMAKE_PREFIX_PATH=$QT5DIR        \
            -DCMAKE_BUILD_TYPE=Release         \
            -DLIB_INSTALL_DIR=lib              \
            -DBUILD_TESTING=OFF                \
            -Wno-dev ..
      make
    popd

EOF

  pushd $packagedir

    cd build
    make install

  popd

  rm -rf $packagedir
  /sbin/ldconfig

done < ../plasma-5.9.2.md5

cd $KF5_PREFIX/share/plasma/plasmoids

for j in $(find -name \*.js); do
  ln -sfv ../code/$(basename $j) $(dirname $j)/../ui/
done

cat >> /etc/pam.d/kde << "EOF"
# Begin /etc/pam.d/kde

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     include        system-auth

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/kde
EOF

cat > /etc/pam.d/kde-np << "EOF"
# Begin /etc/pam.d/kde-np

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     required       pam_permit.so

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/kde-np
EOF

cat > /etc/pam.d/kscreensaver << "EOF"
# Begin /etc/pam.d/kscreensaver

auth    include system-auth
account include system-account

# End /etc/pam.d/kscreensaver
EOF

su -l "$(getent passwd | awk -F: '$3 == 1000 {print $1}')" << EOF
cat > ~/.xinitrc << "EO_nested_F"
ck-launch-session dbus-launch --exit-with-session $KF5_PREFIX/bin/startkde
EO_nested_F
EOF
