URL=(
""
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"gtk+-2.24.31"
"gtk+-3.22.8"
"kde_frameworks-5.31.0"
"libpwquality-1.3.0"
"libxkbcommon-0.7.1"
"mesa-13.0.4"
"networkmanager-1.6.2"
"pulseaudio-10.0"
"python-2.7.13"
"qca-2.1.1"
"taglib-1.11.1"
"xcb-util-cursor-0.1.3"
"libdbusmenu-qt-0.9.3+16.04.20160218"
"libcanberra-0.30"
"libinput-1.6.1"
"linux-pam-1.3.0"
"lm_sensors-3.4.0"
"oxygen-icons5-5.31.0"
"pciutils-3.5.2"
)
