# set up variables from settings.script

source ../settings.script

# set up package variables

PTH=$(dirname $PWD)
PKG=$(basename $PWD)
URL=(
"http://files.itstool.org/itstool/itstool-2.0.2.tar.bz2"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"docbook-xml-4.5"
"python-2.7.11"
)

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root
