# set up variables from settings.script

source ../settings.script

# set up package variables

PTH=$(dirname $PWD)
PKG=$(basename $PWD)
URL=(
"http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.bz2"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"freetype-2.6.3"
)

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root
