PKGVS=$(echo $(basename $PWD) | cut -d - -f 2)
echo $PKGVS

# create build directory

mkdir -v build
cd build

# configure, make and install

../libstdc++-v3/configure           \
    --host=$LFS_TGT                 \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/$PKGVS

make
