URL=(
"http://get.videolan.org/vlc/2.2.4/vlc-2.2.4.tar.xz"
"http://www.linuxfromscratch.org/patches/blfs/8.0/vlc-2.2.4-ffmpeg3-1.patch"
"http://www.linuxfromscratch.org/patches/blfs/8.0/vlc-2.2.4-gcc6_fixes-1.patch"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"alsa-lib-1.1.3"
"ffmpeg-3.2.4"
"liba52-0.7.4"
"libgcrypt-1.7.6"
"libmad-0.15.1b"
"lua-5.3.4"
"xinit-1.3.4"
)
