make install &&
chmod -v 755 /usr/lib/libpython2.7.so.1.0

install -v -dm755 /usr/share/doc/python-2.7.11 &&

tar --strip-components=1                     \
    --no-same-owner                          \
    --directory /usr/share/doc/python-2.7.11 \
    -xvf ../python-2.7.11-docs-html.tar.bz2 &&

find /usr/share/doc/python-2.7.11 -type d -exec chmod 0755 {} \; &&
find /usr/share/doc/python-2.7.11 -type f -exec chmod 0644 {} \;
