# set up variables from settings.script

source ../settings.script

# set up package variables

PTH=$(dirname $PWD)
PKG=$(basename $PWD)
URL=(
"http://people.freedesktop.org/~aplattner/vdpau/libvdpau-1.1.1.tar.bz2"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"xorg_libraries"
)

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root
