# set up variables from settings.script

source ../settings.script

# set up package variables

PTH=$(dirname $PWD)
PKG=$(basename $PWD)
URL=(
"https://launchpad.net/granite/0.3/0.3.1/+download/granite-0.3.1.tar.xz"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"libgee-0.18.0"
)

as_root()
{
  if   [ $EUID = 0 ];        then $*
  elif [ -x /usr/bin/sudo ]; then sudo $*
  else                            su -c \\"$*\\"
  fi
}

export -f as_root
