URL=(
"https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/51.0.1/source/firefox-51.0.1.source.tar.xz"
"http://www.linuxfromscratch.org/patches/blfs/8.0/firefox-51.0.1-system_graphite2_harfbuzz-1.patch"
)

for i in "${URL[@]}"
  do :
    ARC[${#ARC[@]}]=$(basename "$i")
  done

DEP=(
"alsa-lib-1.1.3"
"autoconf-2.13"
"gtk+-3.22.8"
"nss-3.29"
"unzip-6.0"
"yasm-1.3.0"
"zip-3.0"
"icu-58.2"
"libevent-2.1.8"
"libvpx-1.6.1"
"sqlite-3.17.0"
)
